version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.8.1
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./pipeline:/opt/airflow/pipeline
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install -r /requirements.txt &&
              airflow db migrate &&
              airflow users create --username ${_AIRFLOW_WWW_USER_USERNAME} --password ${_AIRFLOW_WWW_USER_PASSWORD} --firstname ${_AIRFLOW_WWW_USER_FIRSTNAME} --lastname ${_AIRFLOW_WWW_USER_LASTNAME} --email ${_AIRFLOW_WWW_USER_EMAIL} --role Admin &&
              airflow webserver"



  airflow-scheduler:
    image: apache/airflow:2.8.1
    depends_on:
      - airflow-webserver
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./pipeline:/opt/airflow/pipeline
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "pip install -r /requirements.txt &&
               airflow scheduler"

volumes:
  postgres_data: